package fr.insset.gestionQCM.dao.entity;

// default package
// Generated 8 mars 2018 16:48:46 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Commentaire generated by hbm2java
 */
@Entity
@Table(name = "commentaire", catalog = "qcm_db")
public class Commentaire implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String textComm;
	private int idQues;
	private int idRep;

	public Commentaire() {
	}

	public Commentaire(String textComm, int idQues, int idRep) {
		this.textComm = textComm;
		this.idQues = idQues;
		this.idRep = idRep;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "TextComm", nullable = false)
	public String getTextComm() {
		return this.textComm;
	}

	public void setTextComm(String textComm) {
		this.textComm = textComm;
	}

	@Column(name = "id_ques", nullable = false)
	public int getIdQues() {
		return this.idQues;
	}

	public void setIdQues(int idQues) {
		this.idQues = idQues;
	}

	@Column(name = "id_rep", nullable = false)
	public int getIdRep() {
		return this.idRep;
	}

	public void setIdRep(int idRep) {
		this.idRep = idRep;
	}

}
