// default package
// Generated 8 mars 2018 16:48:46 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Page generated by hbm2java
 */
@Entity
@Table(name = "page", catalog = "qcm_db")
public class Page implements java.io.Serializable {

	private Integer id;
	private int idQues;

	public Page() {
	}

	public Page(int idQues) {
		this.idQues = idQues;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "id_ques", nullable = false)
	public int getIdQues() {
		return this.idQues;
	}

	public void setIdQues(int idQues) {
		this.idQues = idQues;
	}

}
