// default package
// Generated 8 mars 2018 16:48:46 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Theme generated by hbm2java
 */
@Entity
@Table(name = "theme", catalog = "qcm_db")
public class Theme implements java.io.Serializable {

	private int id;
	private String titreTheme;
	private int idQcm;

	public Theme() {
	}

	public Theme(int id, String titreTheme, int idQcm) {
		this.id = id;
		this.titreTheme = titreTheme;
		this.idQcm = idQcm;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "TitreTheme", nullable = false)
	public String getTitreTheme() {
		return this.titreTheme;
	}

	public void setTitreTheme(String titreTheme) {
		this.titreTheme = titreTheme;
	}

	@Column(name = "id_qcm", nullable = false)
	public int getIdQcm() {
		return this.idQcm;
	}

	public void setIdQcm(int idQcm) {
		this.idQcm = idQcm;
	}

}
